services:
  folderhost:
    container_name: folderhost-server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - folderhost_development_data:/app
    restart: unless-stopped  

  folderhost-client: # Service name
    container_name: folderhost-client
    build: 
      context: ./web # Dockerfile path
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/folderhost-client/src:z
      - ./web/index.html:/folderhost-client/index.html:z
      - ./web/public:/folderhost-client/public:z
    restart: unless-stopped

volumes:
  folderhost_development_data: