package utils

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/MertJSX/folderhost/utils/config"
	"gopkg.in/yaml.v3"
)

func GetConfig() {
	fileData, err := os.ReadFile("./config.yml")

	if err != nil {
		log.Fatalf("Error reading config file: %s", err)
	}

	err = yaml.Unmarshal(fileData, &config.Config)
	if err != nil {
		log.Fatalf("Config.yml parse error: %v", err)
	}

	config.Config.SizeBytes = ConvertStringToBytes(config.Config.StorageLimit)

	config.Config.Folder = strings.TrimPrefix(config.Config.Folder, "./")

	if config.Config.SecretJwtKey == "" ||
		config.Config.SecretJwtKey == "auto" ||
		config.Config.SecretJwtKey == "you must change it" {
		jwtKey, err := GenerateJWTKey()
		if err != nil {
			fmt.Println("Error while generating jwt key, the easiest way to fix it is manually setting the secret jwt key property in config.yml")
			panic(err)
		}
		fmt.Println("New JWT key has been generated!")
		config.Config.SecretJwtKey = jwtKey

		err = UpdateConfigWithNewJWTKey(jwtKey)

		if err != nil {
			fmt.Printf("Error while saving autogenerated JWT key to config.yml: %v\n", err)
		}
	}
}

func UpdateConfigWithNewJWTKey(jwtKey string) error {
	file, err := os.Open("./config.yml")
	if err != nil {
		return fmt.Errorf("can't open config.yml: %w", err)
	}
	defer file.Close()

	var lines []string
	scanner := bufio.NewScanner(file)
	secretUpdated := false

	for scanner.Scan() {
		line := scanner.Text()

		if strings.HasPrefix(strings.TrimSpace(line), "secret_jwt_key:") {
			whitespace := ""
			for _, char := range line {
				if char != ' ' && char != '\t' {
					break
				}
				whitespace += string(char)
			}

			lines = append(lines, fmt.Sprintf(`%ssecret_jwt_key: "%s"`, whitespace, jwtKey))
			secretUpdated = true
		} else {
			lines = append(lines, line)
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("config read error: %w", err)
	}

	if !secretUpdated {
		lines = append(lines, fmt.Sprintf(`secret_jwt_key: "%s"`, jwtKey))
	}

	content := strings.Join(lines, "\n")
	err = os.WriteFile("./config.yml", []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("config write error: %w", err)
	}

	return nil
}
